### ISSUE TITLE
editing windows not aligned horizontally

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#91] opened 2015-11-17 18:12 UTC
Transferring a tangential issue over from isaw.theme issue #33:

Roger and other editors have noticed a problem with the editing window being located incorrectly in the browser window; such that the right side of the content is off-screen, and one has to scroll to the bottom of the page to get a horizontal scroll bar with which to move the editing window into view. It's slowing down editing and causing some confusion for content creators.

**Comment by paregorios** [comment] 2015-11-24 17:22
@k2soule can you get us a screenshot of the problem and post it here? I don't seem to be able to reproduce this problem, which makes me think I'm not understanding. A list of "clicks" necessary to reproduce would also be helpful. Thanks.

**Comment by k2soule** [comment] 2015-11-24 20:03
Sure thing. Attached is a pair of screen shots. The top is how the editing windows appears (with all content and editing tools pushed way to the right, off-screen); the bottom is how it should appear (with all of the content and editing tools visible in the frame).
![editing window](https://cloud.githubusercontent.com/assets/7882896/11379071/6ae3aa08-92bc-11e5-81a3-56d62e375c50.jpg)

**Comment by paregorios** [comment] 2015-11-24 20:12
Aha! This is a problem that is only noticeable when there's a left-side navigation portlet being display perhaps.

**Comment by k2soule** [comment] 2015-11-24 20:53
Yes, that sounds about right. I'm going to guess that the editing view is trying to take up the full width of the window whether there is a side-nav or not. This causes two problems:
First, it causes the annoying issue with the content and tools going off the page.
Second, it makes the page look different while you are editing it than it will look when you publish it - which makes editing tricky. Lines don't break where you expect them to, images don't line up where you expect them to, so you have to guess.

**Comment by skleinfeldt** [comment] 2015-11-24 21:12
Can't help chiming in here to suggest that it is important to wean your editors off planning where line breaks, images, etc. will fall in rich text. Since the site now has a responsive design this will be different at every browser width. When you have the opportunity it might be a good idea to demo to your old school editors the effect of browser resizing on their pages.

Regardless of that, the behavior you describe is certainly a problem!

**Comment by k2soule** [comment] 2015-11-24 21:15
A very good point!

**Comment by paregorios** [comment] 2016-02-17 17:12
bumping to high priority because it causes slow-down and hassle for content creators

**Comment by cewing** [comment] 2016-06-07 00:17
The problem here is caused by a setting in the TinyMCE configuration panel.

The width of the TinyMCE toolbar is currently set to be 1024 pixels.  This forces the rendering of a 1024 pixel wide div to hold the editor toolbar.  The fact of a static width being set on this element causes the editor to overflow the available width on the edit page when portlets are shown in either column (to sometimes hilarious results).  The solution should be to leave this blank or set it to 100%, but that appears not to be possible.  When a non-integer value, no value, or 0 is entered into this setting, the toolbar disappears entirely.  I suggest that we change the setting to a usable value, perhaps 512 (1/2 the current value)

### Suggested Settings

on `/portal_tinymce/@@tinymce-controlpanel`

#### Toolbar Tab

- **Toolbar width**: set to 512

**Comment by paregorios** [comment] 2016-06-07 00:33
This appears to have been implemented on production already, and it appears to be having the desired results. Any objections from @k2soule or @cewing to closing this issue as resolved?

**Comment by cewing** [comment] 2016-06-07 20:10
No objections.  I actually clicked that button myself, so if it has worked, let's mark it closed.

**Comment by k2soule** [comment] 2016-06-07 20:22
I have no objections to closing the ticket.

**Closed** 2016-06-07 20:25 UTC
Labels: enhancement, medium priority, review, style
