### ISSUE TITLE
calendar buttons and grid need tweaks (from isaw.theme)

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#37] opened 2015-08-04 19:10 UTC
Copying this issue over from isaw.theme issue #46:
In calendar view, the Month and Week buttons look unfinished (missing a side border), and the calendar grid is misaligned in Week view.

I think this may be fixed, but I can't tell at the moment (can't see events). I've copied this issue here to remind myself to check.

**Comment by paregorios** [comment] 2015-08-18 15:03
@k2soule ... until we have some event content, I don't think we can check this can we?

**Comment by k2soule** [comment] 2015-08-19 18:58
Actually, now I can see enough to confirm that the styling on the Month and Week buttons has been fixed. However, the calendar Week view itself is still misaligned. The columns don't line up directly under the days.

**Comment by paregorios** [comment] 2015-08-20 23:29
it looks like there are some extra cells (or messed-up colspans) in a couple of the rows in the calendar week view. See screenshot below. I'm taking this ticket to examine markup and CSS to verify exactly what is wrong and determine whether it can be fixed via CSS or if it needs a template modification.

![wonkyweek](https://cloud.githubusercontent.com/assets/263285/9398134/6de9c064-4769-11e5-87d0-711350dbc1ec.jpg)

**Comment by paregorios** [comment] 2015-08-26 18:04
So the header is a completely separate table from the underlying content table. We can probably make this align with CSS. But wow is the base coding a hack.

**Comment by alecpm** [comment] 2016-06-24 18:54
The issues revolved around custom table cell padding in isaw theme. The calendar add-on we're using has very specific cell width requirements and the theme table padding was creating inconsistencies between different parts of the calendar tables. I've overridden the padding customizations for the table views to allow the multi-table layout to come together as expected. The calendar tables are a bit less roomy now, but they should align correctly, and a full day should now appear as intended on the week and day views. This work is deployed to staging.

**Comment by alecpm** [comment] 2016-07-19 07:33
This is merged and deployed

**Closed** 2016-07-21 17:22 UTC
Labels: bug, deploy, high priority, style
