### ISSUE TITLE
image caching problem in news blog and elsewhere

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#39] opened 2015-08-11 20:41 UTC
When I replace the lead image for a news item, it only changes the tile image on the main blog page. The old image remains inside the news item. An example:
https://isaw.nyu.edu/news/isaw-hosts-the-academy-for-teachers

**Comment by paregorios** [comment] 2015-08-18 15:02
@k2soule is this still happening?

**Comment by k2soule** [comment] 2015-08-19 18:03
Still happening. In fact, when I try to reload the /news page on my anonymous browser after making changes in my authenticated browser, it freezes on a blank white screen and can't reload. Also, I'm not sure whether this is related, but several images on news items appear to have lost their cropping data. (the blogtile cropped versions are no longer showing up on the /news listing).

**Comment by paregorios** [comment] 2015-08-20 23:21
There is now a separate ticket (#47) for the loss of cropping problem.

**Comment by paregorios** [comment] 2015-08-20 23:23
Further review of this issue is blocked until we are sure that staging has common code with production so that we can test further.

**Comment by paregorios** [comment] 2015-08-26 17:54
I cannot now reproduce this behavior on staging. 

I visited the main news page in an anonymous tab. In another, authenticated tab, I added a new lead image to a news item and then I cropped it for "blogtiles". Then in the anonymous tab, I hit reload. I saw the new and properly cropped image. Back in the authenticated tab, I replaced the lead image with another one and then adjusted the cropping for it (I noted that the blogtiles view still showed the previous image, but once I'd redone the crop, it was replaced). Back in the anonymous tab, I hit reload and the new and properly cropped image was displayed. 

We will have to be alert for this problem possibly still existing on production.

**Comment by paregorios** [comment] 2015-11-17 17:03
I think this particular error is fixed. @k2soule do you concur? If so, please close.

**Comment by paregorios** [comment] 2016-02-06 13:37
Content folder views had been set to "strong" caching; I downgraded this to "weak" in the hopes of at least reducing this problem from the server perspective. I think we will need to sit with users and watch them do extensive work with the site in the problematic spots to see what happens. In order to prevent browser-side caching by logged-in users, we may need to investigate the selective modification, elimination, or addition of appropriate HTTP response headers over HTTPS connections or for authenticated sessions (the latter is better, since we may someday do everything over https).

**Comment by paregorios** [comment] 2016-02-06 13:48
We may also want to look at changing caching settings for images. There's an "anonymous only" setting, but its use requires specification of headers to pass to the caching proxy. I'd need to know more about how all this works before fooling with it.

**Comment by paregorios** [comment] 2016-02-07 17:34
problem is probably not limited to the news blog; see #43 (which has been closed as a duplicate but has some useful information in comments). I think it remains important that we sit beside e.g. Marc and Maggie while they work so we can see what's happening now.

**Comment by k2soule** [comment] 2016-06-06 17:52
Just assigned this to myself to document an example of this issue, the next time it comes up.

**Comment by paregorios** [comment] 2018-05-25 08:02
@k2soule have you seen this behavior at all recently?

**Comment by paregorios** [comment] 2020-01-13 20:13
As this is a very old ticket and there's been no recent activity, I am going to close it. Please open a new ticket if you spot something happening that looks like this problem.

**Closed by paregorios** 2020-01-13 20:13 UTC
Labels: bug
