### ISSUE TITLE
viewing the images in a publication item

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#189] opened 2016-12-05 22:29 UTC
Related to scrumdo [story number 163](https://www.scrumdo.com/projects/story_permalink/1103909)

Attached are some screen shots showing how a publication item with multiple images currently appears. It is showing the lead image correctly, and thumbnails of the first three additional images, but the thumbnails need to be arranged so that they appear all in a row - rather than two-and-one.

When I click on "See all 5 images", I get a separate viewing window as expected, but the main image appears below the column of thumbnails - rather than next to it.
![pub-item-screenshot](https://cloud.githubusercontent.com/assets/7882896/20904993/f9e5f9b4-bb0f-11e6-85d4-77d40ab265c0.png)
![pub-item-image-box](https://cloud.githubusercontent.com/assets/7882896/20905004/0d6ed2f8-bb10-11e6-9d1f-62efb1ff4351.png)

**Comment by cguardia** [comment] 2016-12-06 01:49
The first thing happens because I forgot to take the portlets into account. I tested it on pages with no portlets. I think we can do one of two things:

1. Use only two images to make sure they will always fit, portlets or no.
2. Use four tile images, which are half the width, which will also fit portlets or no.

The second problem does not happen to me in either firefox or chrome on linux. Which platform are you on?

**Comment by paregorios** [comment] 2016-12-06 18:46
@cguardia for the three images: can we not just force (in CSS) the width of each image to a rounded-down 33% of the width of the lead image and then set the CSS height attribute for each image to "auto" in order to preserve aspect ratio?

**Comment by k2soule** [comment] 2016-12-06 18:48
The issue with the image viewing window seems to be browser-independent; I'm seeing this in chrome and firefox for Mac; but only when viewing on my smaller monitor. When viewing on my large monitor, giving the whole browser window more room, it appears as it's supposed to.

**Comment by cguardia** [comment] 2016-12-08 06:15
I put in fixes for both of these problems, but something is off with the staging js, so the popup is not working. Is anyone testing some new js on staging?

The preview thumbnails should align fine, though.

**Comment by paregorios** [comment] 2016-12-08 11:54
@cguardia I think @alecpm has added the AWLD Javascript on staging ...

**Comment by cguardia** [comment] 2016-12-08 14:05
@alepcm the problem is the js registry is looking for js/awld//lib/requirejs/require.min.js and it's not there.

**Comment by alecpm** [comment] 2016-12-08 18:18
This should be resolved.

**Comment by paregorios** [comment] 2016-12-08 18:20
@k2soule at your earliest opportunity, please have another look at this for review purposes.

**Comment by k2soule** [comment] 2016-12-08 19:17
Looks good on staging.

**Comment by paregorios** [comment] 2016-12-08 20:42
Great! @cguardia I'm going to close this ticket as resolved and I'm going to mark the corresponding story in scrumdo for deployment to production.

**Closed by paregorios** 2016-12-08 20:42 UTC
