### ISSUE TITLE
table class=invisible has gridlines

### ISSUE THREAD

**Issue by paregorios** [isawnyu/isaw.web#78] opened 2015-11-17 17:52 UTC
<a href="https://github.com/paregorios"><img src="https://avatars.githubusercontent.com/u/263285?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [paregorios](https://github.com/paregorios)**
_Friday Sep 04, 2015 at 20:36 GMT_
_Originally opened as https://github.com/isawnyu/isaw.theme/issues/97_

----

**Comment by cewing** [comment] 2016-06-07 23:50
@paregorios this is merged but not yet deployed.  Will assign to you when it is ready for review.

**Comment by cewing** [comment] 2016-06-08 00:17
deployed, in your hands, @paregorios

**Comment by paregorios** [comment] 2016-06-08 12:37
Working great on staging. Please deploy at leisure to production.

**Comment by k2soule** [comment] 2016-06-23 16:55
Checked on production; this looks like it still needs to be deployed.

**Comment by alecpm** [comment] 2016-06-23 18:35
This should be live on production now.

**Comment by k2soule** [comment] 2016-06-24 16:01
Confirmed on production; invisible gridlines are invisible. Closing ticket.

**Closed by k2soule** 2016-06-24 16:01 UTC
Labels: deploy, medium priority, style
