### ISSUE TITLE
permissions and workflow in /news and /events

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#51] opened 2015-09-04 16:15 UTC
Permissions given to user groups on the /news and /events folders are not acting as expected. It appears to be a problem with the workflow policy applied on those folders. When a member of the News Editors group (with can-view, can-add, and can-edit permissions) is logged in, she can't change the publication state of items in the news folder (except for subfolders).

Notes from Tom: this may be related to issue #21. Currently, there's something called "isaw_reviewer_workflow" set for news and events items. It may be the case that content items are being associated with an old custom workflow we are no longer using. Investigating workflows; 
https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows.xml#L28
: https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows.xml#L33

**Comment by paregorios** [comment] 2015-12-09 22:28
I believe the purpose of the special workflows was to make it possible for us to have some users who can create content, but prevent them submitting it for review. We wanted to be able to have a czar (or czars) for the /news and /events folders who would be the only ones allowed to submit for review. Apparently this is not working as designed. I will devise some tests on staging.

**Comment by paregorios** [comment] 2015-12-09 22:37
I have been able to duplicate this problem with test users on staging.

**Comment by paregorios** [comment] 2015-12-09 22:57
I have a suspicion, which we'll need to have Jazkarta help us confirm, deny, or refine, that we just don't know how to designate a person or group to have the special "Reviewer" role (not to be confused with the standard "can review") that's defined in the custom  [isaw_reviewer_workflow](https://github.com/isawnyu/isaw.policy/blob/master/src/isaw/policy/profiles/default/workflows/isaw_standard_workflow/definition.xml), which is bound to /events and /news. I'm going to have a quick look back first through old tickets and stories associated with this feature.

**Comment by paregorios** [comment] 2015-12-09 23:06
Is this related to #46?

**Comment by paregorios** [comment] 2015-12-09 23:12
it is clearly related to #48

**Comment by paregorios** [comment] 2016-01-27 15:31
Users with "can add", "can view", and "can edit" on /news still cannot submit for review. Reopening.

**Comment by paregorios** [comment] 2016-01-27 15:32
It looks like this issue was inadvertantly closed by virtue of a commit message in December. The referenced commit (372cb93) seems irrelevant to this issue.

**Comment by paregorios** [comment] 2016-01-27 15:42
Culprit? https://github.com/isawnyu/isaw.web/blob/master/src/isaw.policy/src/isaw/policy/profiles/default/workflows.xml#L36

**Comment by paregorios** [comment] 2016-01-27 16:37
Path to enlightenment: http://docs.plone.org/4/en/develop/plone/content/workflow.html

**Comment by paregorios** [comment] 2016-01-27 16:37
Plan is:

1. Override these assignments via ZMI -> portal_workflow
2. Figure out how to get them out of code forever.

**Comment by paregorios** [comment] 2016-01-27 22:15
We have successfully set workflow for news items to ```((Default))``` via the ZMI and re-published everything that got blown back to "drafting" as a result. Our editors are now able to submit items as expected. So the follow-up remains: how to make this permanent in code and how to deal with events, where it's also an issue.

**Comment by cewing** [comment] 2016-01-29 18:46
@paregorios the `workflows.xml` file in `isaw.policy`(which you identified in [your comment above](https://github.com/isawnyu/isaw.web/issues/51#issuecomment-175694521) is the file responsible for assigning the default workflow definition and for binding alternate workflows to individual types on a global basis.  So long as the `isaw_reviewer_workflow` is bound to the `NewsItem` and `Event` types in that file, any time an upgrade step that involves workflow is run, that specific workflow will be re-attatched to those types globally.  In order to prevent this from happening, you will want to remove those types from the file (in order to have the default workflow applied automatically).  Then in the future this file will not re-apply that workflow and ruin your hard work.

That being said, there is a better way to redefine workflow assignments than using the ZMI.

First, go to `Site Setup` and click on the `Types` control panel.  You should see something that looks like this:

<img width="484" alt="types_control_panel" src="https://cloud.githubusercontent.com/assets/417109/12684541/5136fa74-c674-11e5-8586-691b1692ada3.png">

In this view, the upper drop-down menu allows you to choose a specific Content Type, the lower one allows you to select from the available workflows.

When you first load the page, the top menu reads `(Default)`, indicating that the lower menu will set the default workflow for any type that does not have a specific workflow set.  

If you select `Event` from the top menu, you should see the lower menu display `isaw_reviewer_workflow` which is the bound workflow for that content type.  If you change the selected value to something else, something **really cool** happens, you get a mapping that lists all the states in the old workflow and provides a dropdown menu for each containing all the states in the new one.  You are allowed then to choose the mapping of old workflow states to new workflow states.  For example, let's pretend the mapping you set up looks like this:

```
Old State    New State
---------    ---------
Published    Published
Reviewing    Reviewing
Draft        Private
```

When you press the `Apply changes` button at the bottom, then Plone will change the workflow assignment globally, crawl your entire site looking for Event objects, change any that are in `Draft` state to `Private` in the new workflow, and reindex all security settings.  

This is the "right way" to change workflow assignments for content types through the web.

Let me know if you have further questions.

**Comment by paregorios** [comment] 2016-01-29 18:53
@cewing thanks!!!!

**Comment by paregorios** [comment] 2016-02-03 15:56
now working on code for this in branch issue51

**Comment by paregorios** [comment] 2016-02-07 17:31
not a director's issue, but leaving high priority as there's a major potential gotcha here if we don't get this locked in code/buildout

**Comment by cewing** [comment] 2016-06-08 18:01
@paregorios or @k2soule could you take a few moments today to summarize from above what needs codification in our codebase?  I'm having trouble following the thread.

**Comment by paregorios** [comment] 2016-06-08 21:04
@cewing what I think we need you to do is to implement the code changes to workflows.xml that [you recommended back in January](https://github.com/isawnyu/isaw.web/issues/51#issuecomment-176905789). Does that make sense?

**Comment by cewing** [comment] 2016-06-08 21:10
Ahhhhhh.  I see what you mean.  The part where I say we have to remove the specific bindings for those types from `workflow.xml` in order to prevent your manual changes from being overwritten.  I'll follow that path.  Thanks for the feedback, @paregorios

**Comment by cewing** [comment] 2016-06-08 21:36
Changes made, awaiting code review and deployment to staging.  Will alert when ready for review, though there's not likely to be anything here to review.

**Comment by alecpm** [comment] 2016-06-08 21:47
It seems to me that maybe this is a case where we should be using CMFPlacefulWorkflow to define a different workflow mapping for /news and /events rather than making a global workflow change. I may not be fully understanding the issue though.

**Comment by paregorios** [comment] 2016-06-08 21:51
We are tying to get rid of the vestiges of an okdbworrkflowbchange.

On Wednesday, June 8, 2016, Alec Mitchell <notifications@github.com> wrote:

> It seems to me that maybe this is a case where we should be using
> CMFPlacefulWorkflow to define a different workflow mapping for /news and
> /events rather than making a global workflow change. I may not be fully
> understanding the issue though.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/isawnyu/isaw.web/issues/51#issuecomment-224739618>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQEdVAjFO5GMf9cN1EwPP2F7pEj-pYhks5qJzh3gaJpZM4F4FQ->
> .
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cewing** [comment] 2016-06-08 21:52
@alecpm I think at one point that may have been true.  My impression at this point is that @paregorios and @k2soule no longer want any `isaw_reviewer_workflow` at all, in any area of the site.  I may be misreading that, though.  

FYI, @paregorios, @k2soule, the changes I've made here are going to be global, which means that throughout the entire site (unless there is a placeful workflow definition sitting in `/news` or `/events`) the News Item and Event content types would no longer be bound to the `isaw_reviewer_workflow`, which is what I thought you were after. Please verify or we can talk it over in person in standup tomorrow to be certain we get this change right.

**Comment by paregorios** [comment] 2016-06-09 00:09
@cewing is correct and I understand the implications he outlines

On Wednesday, June 8, 2016, Cris Ewing <notifications@github.com> wrote:

> @alecpm <https://github.com/alecpm> I think at one point that may have
> been true. My impression at this point is that @paregorios
> <https://github.com/paregorios> and @k2soule <https://github.com/k2soule>
> no longer want any isaw_reviewer_workflow at all, in any area of the
> site. I may be misreading that, though.
>
> FYI, @paregorios <https://github.com/paregorios>, @k2soule
> <https://github.com/k2soule>, the changes I've made here are going to be
> global, which means that throughout the entire site (unless there is a
> placeful workflow definition sitting in /news or /events) the News Item
> and Event content types would no longer be bound to the
> isaw_reviewer_workflow, which is what I thought you were after. Please
> verify or we can talk it over in person in standup tomorrow to be certain
> we get this change right.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/isawnyu/isaw.web/issues/51#issuecomment-224740856>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAQEdUYW5qMR7F4nuM9PTN_GkTan341vks5qJzmTgaJpZM4F4FQ->
> .
>


-- 
-- 
Tom Elliott, Ph.D.
Associate Director for Digital Programs and Senior Research Scholar
Institute for the Study of the Ancient World (NYU)
http://isaw.nyu.edu/people/staff/tom-elliott

**Comment by cewing** [comment] 2016-06-10 16:45
This has been deployed, but is not easy to review, as it only ensures that the workflow settings for NewsItem and Event will not be overwritten when the workflow import step is re-run.  We will have to wait for a change in workflow where we need to rerun that step on upgrade to be able to be sure that this worked (but it does work).

**Comment by paregorios** [comment] 2016-06-10 19:08
Sounds good. Please go ahead and deploy to production.

**Comment by alecpm** [comment] 2016-06-23 18:34
This should be deployed to production now.

**Comment by k2soule** [comment] 2016-06-24 16:36
Thanks! I'm reassigning to Tom for final comment (if any) before closing the ticket, since we may not have an opportunity to review this right away.

**Closed** 2016-07-05 19:41 UTC
Labels: enhancement, review
