### ISSUE TITLE
news items lose cropping info for lead image after edit

### ISSUE THREAD

**Issue by k2soule** [isawnyu/isaw.web#47] opened 2015-08-20 18:59 UTC
News items with a lead image are losing their saved cropping information unexpectedly. We've observed that the blogtile crop selection is lost, and the lead image reverts to showing uncropped on the news blog listing.

We suspect that this happens when an item is edited, but haven't been able to replicate yet.

**Comment by skleinfeldt** [comment] 2015-09-01 15:07
We've used up all our time, and because this is intermittent, can I suggest that we wait to address it until we have reliable instructions to reproduce it?

**Comment by k2soule** [comment] 2015-09-02 21:25
Sounds like a plan. I've made a note to do some more testing later this week.

**Comment by paregorios** [comment] 2016-02-03 21:45
Apparently we are not the only ones seeing this problem: https://github.com/plone/plone.app.mosaic/issues/164

**Comment by skleinfeldt** [comment] 2016-02-03 22:22
FYI, we ran into a horrible problem with p.a.imagecropping losing its crop information at unpredictable times. @alecpm even put some time into it, but without being able to reproduce the problem it was hopeless. I know it happened when something to do with image crops changed but could never isolate it. If you can figure out what causes this it would be awesome.

Thanks for the pointer to that other ticket including reference to  https://github.com/collective/plone.app.imagecropping/commits/recreate-crops ( @alecpm  take a look at that discussion).

**Comment by alecpm** [comment] 2016-06-08 16:29
That mosaic issue provides a good hint as to what might be happening in the cropping machinery. I'll see what I can find. I've deployed the latest release of p.a.imagecropping to staging (we were using a pinned github commit), as it incorporates some fixes that may help here, but doesn't appear to have a definitive fix.

**Comment by skleinfeldt** [comment] 2016-06-08 16:35
@alecpm is this the same problem I kept experiencing on the Jazkarta site? Boy it would be great to find a fix and make p.a.imagecropping more stable...

**Comment by alecpm** [comment] 2016-06-08 22:02
It's definitely the same issue, which is a very tricky one to track down as it seems to occur semi-randomly and without obvious cause.

**Comment by alecpm** [comment] 2016-06-11 00:32
It looks like what was happening is that when an item with image crops is edited, the next request for an uncached image scale triggers a cleanup process that purges any scales/crops that were generated more than 24 hours before the edit. Because the normal scaling mechanism didn't perform the cropping (only the cropping tool saved the crops), once that happens the scales appear un-cropped even though the cropping data is still there.

I've created a branch of p.a.imagecropping and a pull request (https://github.com/collective/plone.app.imagecropping/pull/77) which ensures that whenever scales are recreated they are cropped according to the saved cropping rules. This branch is now deployed on staging (@cewing or @cguardia could you take a sec to review that PR, hopefully someone actively involved in p.a.imagecropping maintenance will take a look as well).

To test I would suggest editing a News Item that has not been recently edited, then visiting the cropping editor. It also might make sense to visit the cropping editor on staging for a page where the crops appear to have gone missing on production. You should be able to reproduce the bug on production by setting/changing a crop on a News Item, waiting 24 hours, editing and saving the News Item and then visiting the cropping page once or twice (there's a race condition on that might prevent you from seeing the issue on the first load).

**Comment by paregorios** [comment] 2016-06-11 08:08
@k2soule would you please take the lead on reviewing this item?

**Comment by paregorios** [comment] 2016-09-06 16:36
closing as resolved. We will open new tickets if we run into additional problems.

**Closed by paregorios** 2016-09-06 16:36 UTC
Labels: bug, high priority, review
